language: php

php:
  - '5.6'
  - '7.0'

install:
  - sudo apt-get update
  - sudo apt-get install -y --force-yes libssh2-php

before_script:
  - php -t ./web/ -S 127.0.0.1:7001 &
  - until netstat -an 2>/dev/null | grep '7001.*LISTEN'; do true; done

script: phpunit web
